name: receive_sharing_intent_web_example
description: "Demonstrates how to use the receive_sharing_intent_web plugin."
publish_to: 'none'

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  share_plus: ^7.2.2
  receive_sharing_intent: ^1.6.7
  receive_sharing_intent_web:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
